app = "local-ip"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "53"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 53
  protocol = "udp"

  [[services.ports]]
    port = "53"
